server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.115.89:3307/yue_ke_wei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

token:
  sign: HANZOY@YUEKEWEI_SIPC115
  time: 60*60*24*7

wechat:
  appid: wx192b37f3cf001415
  secret: 507cf12c3ac01e64a038b248df28fe32