server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://49.232.223.89:50013/yue_ke_wei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/yue_ke_wei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://192.168.115.89:3307/yue_ke_wei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://123.56.217.92:3306/yue_ke_wei?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

token:
  sign: HANZOY@YUEKEWEI_SIPC115
  time: 60*60*24*7

wechat:
  appid: wxf0a04263dffa3f3f
  secret: 8060461ebd80e175208d3a4e9faeb537